version: "3.3"

services:
    api:
        build:
            context: .
        image: oemail
        working_dir: /app
        env_file: docker-compose.env
        expose:
            - 3000
        ports:
            - 3000:3000
        depends_on:
            - redis
            - mongo

    mongo:
        image: mongo:4
        volumes:
            - data:/data/db
        expose:
            - "27017"
        ports:
            - "27017:27017"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    data:
